# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43c5991963f25a4a1f0cafd27652a8287a71bd37253d4d52cfca4cd17844ea0b7b5287ef304f2bb677a77397fef8a77ed959b23451b80fb81d172b201ec95bdc

test:
  secret_key_base: c4d3d48d9b652f5135e23fe8bbd1c7f9cf9ecfbebb04b44e54acea8cfa70ac07133f3f060f5f3d63ed62a56543761057722ba6b003bc5ef079f62f07304fb34f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
